import { createClient } from '@supabase/supabase-js';
import { createHash } from 'node:crypto';
import { scrubObject } from './sentry-pii';

// Closed catalog of event_types. New events should be added here so the SLA
// dashboard / queries know what to look for. Free-form strings still work but
// won't be auto-classified.
export type AuditEventType =
  | 'schedule_created'
  | 'schedule_retried'
  | 'message_sent'
  | 'message_failed'
  | 'tier_changed'
  | 'webhook_received'
  | 'auth_login'
  | 'auth_logout'
  | 'payment_event'
  | (string & {});

interface AuditEventParams {
  userPhone?: string | null;
  eventType: AuditEventType;
  payload?: Record<string, unknown>;
  ipAddress?: string | null;
}

// SHA-256 truncated to 8 hex chars. Suitable for opaque dedup tokens in audit
// payloads (e.g. correlating two events about the same contact_number) WITHOUT
// storing the cleartext. Not a cryptographic identifier.
export async function hashContactRef(value: string): Promise<string> {
  if (!value) return 'h:00000000';
  const bytes = new TextEncoder().encode(value);
  const digest = await globalThis.crypto.subtle.digest('SHA-256', bytes);
  const arr = new Uint8Array(digest);
  let hex = '';
  for (let i = 0; i < 4; i++) hex += arr[i].toString(16).padStart(2, '0');
  return 'h:' + hex;
}

// Phone redaction for LLM prompts. The admin/chat endpoint ships per-user rows
// to Groq/OpenAI for natural-language operator queries; sending raw E.164
// numbers would leak PII to third-party LLM providers. The masked form keeps a
// 6-char SHA-256 prefix (for operator dedup across rows) plus the last 4
// digits (so the operator can still match a row against a phone they already
// know from another source). Sync `node:crypto` because the call site at
// admin/chat/route.ts:45-51 is a `.map()` over result rows.
export function maskPhoneForLLM(phone: string): string {
  if (!phone || phone.length < 4) return '[REDACTED]';
  const last4 = phone.slice(-4);
  const hash = createHash('sha256').update(phone).digest('hex').slice(0, 6);
  return `[#${hash}…${last4}]`;
}

// Masks WhatsApp instance names (SchedWhats-<E.164>) embedded in free text that
// is about to be sent to a 3rd-party LLM (e.g. the admin assistant's system-check
// messages). The phone inside the instance name gets the same maskPhoneForLLM
// treatment as every other phone in that context, so a full number never leaks.
export function maskInstanceNamesForLLM(text: string): string {
  if (!text) return text;
  return text.replace(/SchedWhats-(\d{6,15})/g, (_m, phone) => 'SchedWhats-' + maskPhoneForLLM(phone));
}

// Synchronous mirror of hashContactRef. The webhook dbLog scrubber runs in
// Node runtime and needs to hash phones/names inside a tight loop over
// payload keys — going async would force every caller to await. Output
// format matches hashContactRef exactly ('h:' + 8 hex chars) so dedup tokens
// generated by either function correlate cleanly in queries.
export function hashContactRefSync(value: string): string {
  if (!value) return 'h:00000000';
  const hex = createHash('sha256').update(value).digest('hex').slice(0, 8);
  return 'h:' + hex;
}

// Fire-and-forget audit write. Never throws — failures are logged as warnings
// so the primary request path is never blocked by audit infrastructure.
// Returns a Promise the caller can choose to await (most do; cron paths
// can `void` it when latency is critical).
export async function logAuditEvent(params: AuditEventParams): Promise<void> {
  try {
    const url = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL;
    const key = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
    if (!url || !key) {
      console.warn('AUDIT: missing Supabase credentials, skipping event=' + params.eventType);
      return;
    }
    const supabase = createClient(url, key);
    const { error } = await supabase.from('audit_events').insert({
      user_phone: params.userPhone || null,
      event_type: params.eventType,
      payload: scrubObject(params.payload || {}), // M: keep phone/JID/email out of audit JSONB
      ip_address: params.ipAddress || null,
    });
    if (error) {
      console.warn('AUDIT: insert failed event=' + params.eventType + ' err=' + error.message);
    }
  } catch (err) {
    console.warn('AUDIT: log threw event=' + params.eventType + ' err=' + (err as Error)?.message);
  }
}

// Helper to extract client IP from a Next.js request. Vercel uses
// x-forwarded-for; fall back to x-real-ip; null if neither.
export function clientIpFromHeaders(headers: { get: (name: string) => string | null }): string | null {
  const fwd = headers.get('x-forwarded-for');
  if (fwd) return fwd.split(',')[0].trim();
  return headers.get('x-real-ip');
}
